convert paths to arrays
mavoweb/treecle pull request #16
Opened 2024-03-05 18:33 UTC by adamjanicki2

Converts all paths to arrays and closes #6

2024-03-05 19:06 UTC, LeaVerou requested changes
It's not that simple I'm afraid 😄 

If we’re using paths, we can't be doing things that assume the path is of length <=2 like: 

```
const [property, index] = path;
// ...
parent[property][index] = newChild;
```

We need to instead implement util functions that take an object and a path and get/set it.

2024-03-05 19:15 UTC, LeaVerou commented
Just pushed two util methods to help you do this!

2024-03-05 19:39 UTC, adamjanicki2 commented
> Just pushed two util methods to help you do this!
> 
> (Have not tested them, feel free to make any changes needed)

Just thinking here -- do we want to export the `get` helper to authors? I think it would be useful. We could stick it in `path.js` along with a function that finds the path between two nodes. The `set` helper should remain private since it becomes complicated with parent pointers and pretty much only works when we use it internally within a function like this

2024-03-06 15:55 UTC, LeaVerou commented
> > Just pushed two util methods to help you do this!
> > (Have not tested them, feel free to make any changes needed)
> 
> Just thinking here -- do we want to export the `get` helper to authors? I think it would be useful. We could stick it in `path.js` along with a function that finds the path between two nodes. The `set` helper should remain private since it becomes complicated with parent pointers and pretty much only works when we use it internally within a function like this

Not sure what you mean, these are already exported and they can import them?

2024-03-06 15:56 UTC, LeaVerou commented on src/childPaths.js
> +				let childPaths = child.map((c, index) => ({node: c, path: [property, index]}));
Is this still assuming a (max) two-part path?

2024-03-06 15:58 UTC, LeaVerou requested changes
I think a lot of this still assumes a shallow path.
Try to use your code with cases where to get from each node to each children you have to follow something like `foo.bar.baz`. I haven't looked *super* closely, but from a first skim, I don't think it would work.

2024-03-06 16:19 UTC, adamjanicki2 commented
> I think a lot of this still assumes a shallow path. Try to use your code with cases where to get from each node to each children you have to follow something like `foo.bar.baz`. I haven't looked _super_ closely, but from a first skim, I don't think it would work.

Would this even be allowed? In what cases could you follow two object properties and get to a child? In the case of `foo.bar.baz`, how could `baz` be a direct child of `foo`?

2024-03-06 21:54 UTC, adamjanicki2 commented
My thinking was we sort of have to enforce the fact that children can only be accessed via a property, or a property and an index in the case of an array; otherwise having arbitrary ways of accessing children would defeat the difference between children and descendants in general

2024-03-07 14:26 UTC, LeaVerou commented
What’s the point of making the path an array then?

2024-03-11 18:13 UTC, LeaVerou approved these changes
Rethinking this, I think it's fine to move towards a `path` now, and make the code more generic as use cases emerge. As discussed, we should not assume that the second property is an index, since we already have use cases where it isn’t.

2024-03-11 18:22 UTC, merged